Ga_AGV.Core/Controllers/AGVSystemController.cs
using Ga_AGV.BLL;
using Ga_AGV.Model.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ga_AGV.Core.Controllers
{
    public class AGVSystemController : Controller
    {
        private Ga_settingBLL ga_Setting = new Ga_settingBLL();

        // GET: AGVSystem
        [Authorize]
        public ActionResult QR_Code()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult AGVMonitoring()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

Ga_AGV.Core/Controllers/ConfigurationController.cs
using Ga_AGV.BLL;
using Ga_AGV.Model.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ga_AGV.Core.Controllers
{
    public class ConfigurationController : Controller
    {
        Ga_settingBLL ga_Setting = new Ga_settingBLL();

        /// <summary>
        /// 系统配置
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                List<Ga_setting> ga_s = ga_Setting.Ga_Settings();
                return View(ga_s);
            }
        }
    }
}

Ga_AGV.Core/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ga_AGV.Core.Controllers
{
    public class EquipmentController : Controller
    {
        // GET: Equipment
        [Authorize]
        public ActionResult AGVManagement()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

Ga_AGV.Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ga_AGV.Core.Controllers
{
    public class HomeController : Controller
    {

        /// <summary>
        /// 登录
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// 主页
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Main()
        {
           return View();
        }
    }
}

Ga_AGV.Core/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ga_AGV.Core.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        [Authorize]
        public ActionResult RunningLog()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult TaskLog()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }
        [Authorize]
        public ActionResult Rack()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        /// AGV状态
        /// </summary>
        /// <returns></returns>
         [Authorize]
        public ActionResult AGVState()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }


        [Authorize]
        public ActionResult RunMonitoring()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult StatisticsData()
        {
            if (Request.ServerVariables["HTTP_REFERER"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Statisti()
        {
            return View();
        }
    }
}

Ga_AGV.Core/Views/AGVSystem/AGVMonitoring.cshtml
@{
    ViewBag.Title = "AGVMonitoring";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    ViewBag.PageTitle = "AGV系统";
    ViewBag.PageColumn = "运行监控";
}
<link href="~/Content/AGVMonitoring.css" rel="stylesheet" />
<div>
    <div class="count-panel" style="width:100%;margin:0px auto;">
        <div class="panel panel-default">
            <div class="panel-heading " id="pal-text"><span class="glyphicon glyphicon-tower" aria-hidden="true"></span>&nbsp;AGV监控</div>
            <div class="panel-body">
                <div class="Control-lefts">
                    <div class="form-group">
                        <button id="button_all" type="button" class="btn btn-primary">显示全部AGV</button>
                    </div>
                    <div class="form-group">
                        <select id="combobox_agv" class="selectpicker show-tick form-control" data-live-search="true"></select>
                    </div>
                    <div class="count-panel" style="padding:3px;text-align:center;">
                        <div class="x_title">
                            <h2 style="font-size:18px;margin-top:10px;">基本信息</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix">
                            <div style="width:100%;">
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">编号</li>
                                    <li class="clearfix-count" id="agvNum">1号</li>
                                    <li class="clearfix-li">状态</li>
                                    <li class="clearfix-count" id="agvIsRunning">在线</li>
                                </ul>
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">二维码</li>
                                    <li class="clearfix-count clearfix-width info-width" id="qrcode">1</li>
                                </ul>
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">PBS</li>
                                    <li class="clearfix-count" id="PBS">区域1</li>
                                    <li class="clearfix-li">云台</li>
                                    <li class="clearfix-count" id="agvHolder">上升</li>
                                </ul>
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">报警信息</li>
                                    <li class="clearfix-count clearfix-width info-width" id="Message">正常</li>
                                </ul>
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">当前位置</li>
                                    <li class="clearfix-count" id="agvQR">1</li>
                                    <li class="clearfix-li">当前任务</li>
                                    <li class="clearfix-count" id="Task">运输</li>
                                </ul>
                                <ul class="Control-li clearfix-ul">
                                    <li class="clearfix-li">出发地</li>
                                    <li class="clearfix-count" id="taskStartQR">1</li>
                                    <li class="clearfix-li">目的地</li>
                                    <li class="clearfix-count" id="taskEndQR">1</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Control-right">
                    <canvas id="canvas" style="border:#EDEDED solid 1px">您当前的浏览器版本不支持此功能</canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    var Wid = 0; var Hei = 0; var ShowAgvInfo; var ShowAgvInfo_all;
    var ar = new Array();

    $(function () {
        $.ajax({
            type: "post",
            url: "/api/agvlist/agv",
            success: function (data) {
                $.each(data, function (index, item) {
                    $("<option value=' " + item.agvNum + "'>AGV " + item.agvNum + "</option>").appendTo("#combobox_agv.selectpicker");//用appendTo声明是给谁的值
                });
                $('#combobox_agv').selectpicker('refresh');
            }
        });

        $.ajax({
            url: '/api/AGVSystem/ShowPlace',
            type: "post",
            contentType: 'application/json',
            success: function (data) {
                Wid = data.map_X; Hei = data.map_Y;
                ShowQR(Wid, Hei, data.rows);
                ShowAgvInfo_all = setInterval(function () {
                    ShowAGV_all(data.rows);
                }, 1000);
                for (var i = 0; i < data.rows.length; i++) {
                    ar.push(data.rows[i])
                }
                //console.log(ar);
            }
        });

        $("#button_all").click(function () {
            clearInterval(ShowAgvInfo_all); clearInterval(ShowAgvInfo);
            ShowAgvInfo_all = setInterval(function () {
                ShowAGV_all(ar);
            }, 1000);
        });

        $("#combobox_agv").on('change', function () {
            clearInterval(ShowAgvInfo_all); clearInterval(ShowAgvInfo);
            ShowAgvInfo = setInterval(function () {
                ShowAGV(ar, document.getElementById("combobox_agv").value);
            }, 1000);
        });

        function ShowQR(Wid, Hei, ar) {
            var canvas = document.getElementById('canvas');
            canvas.width = Wid;
            canvas.height = Hei;
            if (canvas.getContext) {
                var ctx = canvas.getContext("2d"),
                    width = canvas.width,
                    height = canvas.height;
                for (var i = 0; i < ar.length; i++) {
                    ctx.beginPath();
                    ctx.arc(ar[i].qrX, ar[i].qrY, (Wid / 65), 0, 2 * Math.PI, false);
                    ctx.closePath(); //关闭路径
                    if (ar[i].qrStatus == 1) {
                        ctx.fillStyle = "#528B8B";
                    } else {
                        ctx.fillStyle = "red";
                    }
                    ctx.fill();//填充
                    ctx.font = "10pt 微软雅黑";
                    ctx.fillStyle = "#E6E6FA";
                    ctx.textAlign = 'center';
                    ctx.textBaseline = 'middle';
                    ctx.fillText(ar[i].qrInfo, ar[i].qrX, ar[i].qrY);
                }
            }
        };

        function ShowAGV(ar, Num) {
            $.ajax({
                url: '/api/AGVSystem/AGVlocation',
                type: "post",
                data: JSON.stringify({ "agvNum": agvNum }),
                contentType: 'application/json',
                success: function (data) {
                    console.log(data[Number(Num) - 1]);
                    $("#agvNum").text(data[Number(Num) - 1].agvNum);
                    $("#agvIsRunning").text(data[Number(Num) - 1].agvIsRunning);
                    $("#qrcode").text(data[Number(Num) - 1].qrcode);
                    $("#PBS").text(data[Number(Num) - 1].PBS);
                    $("#agvHolder").text(data[Number(Num) - 1].agvHolder);
                    $("#Message").text(data[Number(Num) - 1].Message);
                    $("#agvQR").text(data[Number(Num) - 1].agvQR);
                    $("#Task").text(data[Number(Num) - 1].Task);
                    $("#taskStartQR").text(data[Number(Num) - 1].taskStartQR);
                    $("#taskEndQR").text(data[Number(Num) - 1].taskEndQR);
                    var canvas = document.getElementById('canvas');
                    var ctx = canvas.getContext("2d");
                    var img = new Image();
                    if (data.Message != "正常") { img.src = "../Scripts/AGVSystem/agv机器人红.jpg" }
                    else { img.src = "../Scripts/AGVSystem/agv机器人蓝.jpg" }
                    ShowQR(Wid, Hei, ar);
                    ctx.drawImage(img, ar[data[Number(Num) - 1].agvQR].qrX - 25, ar[data[Number(Num) - 1].agvQR].qrY - 25, 50, 50);
                }
            });
        };

        function ShowAGV_all(ar) {
            $.ajax({
                url: '/api/AGVSystem/AGVlocation',
                type: "post",
                data: JSON.stringify({ "agvNum": agvNum }),
                contentType: 'application/json',
                success: function (data) {
                    //console.log(data);
                    $("#agvNum").text(data[0].agvNum);
                    $("#agvIsRunning").text(data[0].agvIsRunning);
                    $("#qrcode").text(data[0].qrcode);
                    $("#PBS").text(data[0].PBS);
                    $("#agvHolder").text(data[0].agvHolder);
                    $("#Message").text(data[0].Message);
                    $("#agvQR").text(data[0].agvQR);
                    $("#Task").text(data[0].Task);
                    $("#taskStartQR").text(data[0].taskStartQR);
                    $("#taskEndQR").text(data[0].taskEndQR);
                    var canvas = document.getElementById('canvas');
                    var ctx = canvas.getContext("2d");
                    var img = new Image();
                    ShowQR(Wid, Hei, ar);//重绘二维码画布
                    $.each(data, function (index, item) {
                        if (item.Message != "正常") { img.src = "../Scripts/AGVSystem/agv机器人红.jpg" }
                        else { img.src = "../Scripts/AGVSystem/agv机器人蓝.jpg" }
                        ctx.drawImage(img, ar[item.agvQR - 1].qrX - 25, ar[item.agvQR - 1].qrY - 25, 50, 50);

                        console.log(data[index]);
                        ctx.font = "bold 12pt 微软雅黑";
                        ctx.fillStyle = "#0A0A0A";
                        ctx.textAlign = 'center';//center
                        ctx.textBaseline = 'Bottom';//middle
                        ctx.fillText(data[index].agvNum, ar[item.agvQR - 1].qrX, ar[item.agvQR - 1].qrY);
                    });
                }
            });
        };
    })
</script>

Ga_AGV.Core/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>用户登录</title>
    <link href="~/Scripts/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/bootstrap-3.3.7/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Login.css" rel="stylesheet" />
    <link href="~/Scripts/toastr-master/toastr.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/toastr-master/toastr.min.js"></script>
</head>
<body>
    <div>
        <div class="main-bg">
            <img src="~/image/bg.png" />
        </div>
        <div class="main-count">
            <div class="main-top">
                <img src="~/image/logo.png" />
            </div>
            <div class="main-middle">
                <div class="main-middle-count">AGV智能调度系统</div>
            </div>
            <div class="main-centre ">
                <div class="main-centre-count" >
                    <form method="POST" role="form" id="form-test" >
                        <div class="form-group main-group">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user"></span></span>
                                <input type="text" id="UserName" name="UserName" class="form-control" placeholder="请输入账号" aria-describedby="basic-addon1">
                            </div>
                        </div>
                        <div class="form-group main-group">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon2"><span class="glyphicon glyphicon-lock"></span></span>
                                <input type="password" id="Password" name="Password" class="form-control" placeholder="请输入密码" aria-describedby="basic-addon2">
                            </div>
                        </div>
                        <div class="form-group main-form">
                            <div class="input-group inut-main">
                                <button id="btn-test"  style="background-color: #ffba19;color:white;font-weight:bold" class="btn  btn-block" type="button">登&nbsp;录</button>
                            </div>
                        </div>
                        <div class="main-bottom">
                            <p>
                                Copyright &copy;
                                <script>document.write((new Date()).getFullYear());</script>  Galaxis
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {

            $('#btn-test').click(function () {
                if ($('#UserName').val() == "" || $('#Password').val() == "") {
                    toastr.error('账号密码不能为空！');
                    return;
                }
                $.ajax({
                    type: 'post',
                    url: '/api/agvlogin/LoginUser',
                    contentType: 'application/json',
                    data: JSON.stringify({ "userName": $('#UserName').val(), "userPassword": $('#Password').val() }),
                    datatype: 'json',
                    success: function (res) {
                        if (res.Success) {
                            toastr.info(res.Message);
                            setTimeout(function () {
                                window.location.href = "/Statistics/StatisticsData";
                            }, 100);
                        }
                        else {
                            toastr.error(res.Message);
                        }
                    },
                    error: function (e) {
                        toastr.error(e.responseText);
                    }
                });
            });
        });

        document.body.addEventListener('keyup', function (e) {
            if (e.keyCode == '13') {
                $('#btn-test').trigger("click");
            }
        });

    </script>
</body>
</html>

Ga_AGV.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ga_AGV.Core/Views/Statistics/StatisticsData.cshtml
@{
    ViewBag.Title = "StatisticsData";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    ViewBag.PageTitle = "统计数据";
    ViewBag.PageColumn = "统计报表";
}
<link href="~/Content/StatisticsData.css" rel="stylesheet" />
<ol class="breadcrumb">
    <li><span style="color:#337ab7;">首页</span></li>
</ol>
<div class="Top-Count">
    <div class="fen-left">
        <div class="count-panel" style="width:100%;margin:0px auto;padding-top:5px;">
            <div class="x_title">
                <h2 style="font-size:16px;">快捷菜单</h2>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix">
                <div>
                    <div class="fonyr-pou">
                        <dl class="tent"  style="margin-top:2px;">
                            <dt><a href="@Url.Action("Rack","Statistics")#nav1"><i class="icon-size fa fa-server"></i></a></dt>
                            <dd>货架管理</dd>
                        </dl>
                        <dl class="tent"  style="margin-top:2px;">
                            <dt><a href="@Url.Action("AGVManagement","Equipment")#nav2"><i class="icon-size fa fa-cog"></i></a></dt>
                            <dd>AGV管理</dd>
                        </dl>
                        <dl class="tent tent-right"  style="margin-top:2px;">
                            <dt><a href="@Url.Action("AGVMonitoring","AGVSystem")#nav4"><i class="icon-size fa fa-external-link-square"></i></a></dt>
                            <dd>AGV状态</dd>
                        </dl>
                        <dl class="tent tent-right"  style="margin-top:2px;">
                            <dt><a href="@Url.Action("RunningLog","Statistics")#nav3"><i class="icon-size fa fa-hourglass-2"></i></a></dt>
                            <dd>运行日志</dd>
                        </dl>
                        <dl class="tent">
                            <dt><a href="@Url.Action("TaskLog","Statistics")#nav3"><i class="icon-size fa fa-paper-plane"></i></a></dt>
                            <dd>任务日志</dd>
                        </dl>
                        <dl class="tent">
                            <dt><a href="@Url.Action("AGVMonitoring","AGVSystem")#nav4"><i class="icon-size fa fa-desktop"></i></a></dt>
                            <dd>运行监控</dd>
                        </dl>
                        <dl class="tent">
                            <dt><a href="@Url.Action("QR_Code","AGVSystem")#nav4"><i class="icon-size fa fa-qrcode"></i></a></dt>
                            <dd>二维码</dd>
                        </dl>
                        <dl class="tent">
                            <dt><a href="@Url.Action("Index","Configuration")"><i class="icon-size fa fa-map"></i></a></dt>
                            <dd>系统配置</dd>
                        </dl>
                        <div class="clear"></div>
                    </div>
                </div>
                <div>

                </div>
            </div>
        </div>
    </div>
    <div class="fen-Right">
        <div class="count-panel" style="width:100%;margin:0px auto;padding-top:5px;">
            <div class="x_title">
                <h2 style="font-size:16px;">待办事项</h2>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix" style="text-align:center">
                <div style="padding: 5px;">
                    <dl class="bloct-count menus" style="margin-bottom: 0px;">
                        <dt class="bloct-cou ">待处理故障</dt>
                        <dt class="backlog-body bloct-cou">100</dt>
                    </dl>
                    &nbsp;
                    <dl class="bloct-count menus" style="margin-bottom: 0px;">
                        <dt class="bloct-cou ">待处理故障</dt>
                        <dt class="backlog-body bloct-cou">10</dt>
                    </dl>
                </div>
                <div style="padding: 5px;">
                    <dl class="bloct-count menus" style="margin-bottom: 0px;">
                        <dt class="bloct-cou">待处理故障</dt>
                        <dt class="backlog-body bloct-cou">5</dt>
                    </dl>
                    &nbsp;
                    <dl class="bloct-count menus" style="margin-bottom: 0px;">
                        <dt class="bloct-cou ">待处理故障</dt>
                        <dt class="backlog-body bloct-cou">6</dt>
                    </dl>
                </div>
                <div>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="coun-right">
    <div class="count-panel" style="width:100%;margin:0px auto;height:265px;padding-top:5px;">
        <div class="x_title">
            <h2 style="font-size:16px;">网络状态</h2>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix">
            <table class="table table-bordered">
                <tr>
                    <td width="180" style="font-size:15px;text-align:center;color:#808080">监听IP</td>
                    <td style="font-size:16px;text-align:center;color: #0565b7" id="Address">-</td>
                </tr>
                <tr>
                    <td width="180" style="font-size:15px;text-align:center;color:#808080">监听端口</td>
                    <td style="font-size:16px;text-align:center;color: #0565b7;" id="Port">-</td>
                </tr>
                <tr>
                    <td width="180" style="font-size:15px;text-align:center;color:#808080">最大连接数</td>
                    <td style="font-size:16px;text-align:center;color: #0565b7;" id="maxConnect">-</td>
                </tr>
                <tr>
                    <td width="180" style="font-size:15px;text-align:center;color:#808080">在线数量</td>
                    <td style="font-size:16px;text-align:center;color: #0565b7;" id="OnClientCount">-</td>
                </tr>
                <tr>
                    <td width="180" style="font-size:15px;text-align:center;color:#808080">连接状态</td>
                    <td style="font-size:16px;text-align:center;color: #0565b7;" id="IsRunning">-</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="count-main-left" id="container">

</div>
@*<div class="count-main-right" id="containers">

    </div>*@
<script>
    var chart = Highcharts.chart('container', {
        chart: {
            type: 'spline'
        },
        title: {
            text: '运行统计'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: ['一月', '二月', '三月', '四月', '五月', '六月',
                '七月', '八月', '九月', '十月', '十一月', '十二月']
        },
        yAxis: {
            title: {
                text: '任务数/距离'
            },
            labels: {
                formatter: function () {
                    return this.value;
                }
            }
        },
        tooltip: {
            crosshairs: true,
            shared: true
        },
        plotOptions: {
            spline: {
                marker: {
                    radius: 4,
                    lineColor: '#666666',
                    lineWidth: 1
                }
            }
        },
        series: [{
            name: 'AGV执行任务数',
            marker: {
                symbol: 'square'
            },
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 20, 23.3, 18.3, 13.9, 9.6]
        }, {
            name: 'AGV运行距离',
            marker: {
                symbol: 'diamond'
            },
            data: [50, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
    });

    //var chart = Highcharts.chart('containers', {
    //    chart: {
    //        type: 'pie',
    //        options3d: {
    //            enabled: true,
    //            alpha: 45
    //        }
    //    },
    //    title: {
    //        text: '简数科技每周水果消耗量'
    //    },
    //    subtitle: {
    //        text: ''
    //    },
    //    plotOptions: {
    //        pie: {
    //            innerSize: 100,
    //            depth: 45
    //        }
    //    },
    //    series: [{
    //        name: '货物金额',
    //        data: [
    //            ['香蕉', 8],
    //            ['猕猴桃', 3],
    //            ['桃子', 1],
    //            ['橘子', 6],
    //            ['苹果', 8],
    //            ['梨', 4],
    //            ['柑橘', 4],
    //            ['橙子', 1],
    //            ['葡萄 (串)', 1]
    //        ]
    //    }]
    //});
    agvinfo();

    var updates = setInterval(function () {
        agvinfo();
    }, 800);

    function agvinfo() {
        $.ajax({
            type: 'post',
            url: '/api/Services/Socket',
            contentType: 'application/json',
            datatype: 'json',
            success: function (res) {
                if (res.Address != "0") {
                    $('#Address').text(res.Address);
                    $('#Port').text(res.Port);
                    $('#maxConnect').text(res.maxConnect);
                    if (res.IsRunning) {
                        $('#IsRunning').text("监听中");
                    }
                    else {
                        $('#IsRunning').text("断开");
                    }
                    $('#OnClientCount').text(res.OnClientCount);
                } else {
                    $('#Address').text('-');
                    $('#Port').text('-');
                    $('#maxConnect').text('-');
                    $('#IsRunning').text('-');
                    $('#OnClientCount').text('-');
                    clearInterval(updates);
                }
            },
            error: function (e) {
                toastr.error(e.responseText);
                clearInterval(updates);
            }
        });
    }

</script>